// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh93rHiVZEpwYL06RhEayjaGLY-ZbO6s8',
    appId: '1:681229938331:web:57ccc5dc8c722372a4a03e',
    messagingSenderId: '681229938331',
    projectId: 'usuarios-fea58',
    authDomain: 'usuarios-fea58.firebaseapp.com',
    storageBucket: 'usuarios-fea58.firebasestorage.app',
    measurementId: 'G-M8X3RN271L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlAIlVyftIHmyZ7aS4kU2H7w0o2BDz5nk',
    appId: '1:681229938331:android:3146ea8d838ac192a4a03e',
    messagingSenderId: '681229938331',
    projectId: 'usuarios-fea58',
    storageBucket: 'usuarios-fea58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7NRXxnvkPv94B6WscJZ4sUQ3tLgQXGOc',
    appId: '1:681229938331:ios:94b73d11f045484fa4a03e',
    messagingSenderId: '681229938331',
    projectId: 'usuarios-fea58',
    storageBucket: 'usuarios-fea58.firebasestorage.app',
    iosBundleId: 'com.example.uge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7NRXxnvkPv94B6WscJZ4sUQ3tLgQXGOc',
    appId: '1:681229938331:ios:94b73d11f045484fa4a03e',
    messagingSenderId: '681229938331',
    projectId: 'usuarios-fea58',
    storageBucket: 'usuarios-fea58.firebasestorage.app',
    iosBundleId: 'com.example.uge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh93rHiVZEpwYL06RhEayjaGLY-ZbO6s8',
    appId: '1:681229938331:web:56ffe94b639fa2bfa4a03e',
    messagingSenderId: '681229938331',
    projectId: 'usuarios-fea58',
    authDomain: 'usuarios-fea58.firebaseapp.com',
    storageBucket: 'usuarios-fea58.firebasestorage.app',
    measurementId: 'G-2FN25WV7QH',
  );

}